apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p0ik7xt42-go
  janus-idp.io/tekton: p0ik7xt42-go
  backstage.io/kubernetes-id: p0ik7xt42-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p0ik7xt42-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
